# Prettier-friendly markdownlint config that mirrors markdownlint/style/prettier.
# Declaring the rules inline keeps trunk self-contained and avoids depending on
# markdownlint/style resolution from a Node install.
default: true
blanks-around-fences: false
blanks-around-headings: false
blanks-around-lists: false
code-fence-style: false
emphasis-style: false
heading-start-left: false
hr-style: false
line-length: false
list-indent: false
list-marker-space: false
no-blanks-blockquote: false
no-hard-tabs: false
no-missing-space-atx: false
no-missing-space-closed-atx: false
no-multiple-blanks: false
no-multiple-space-atx: false
no-multiple-space-blockquote: false
no-multiple-space-closed-atx: false
no-trailing-spaces: false
ol-prefix: false
strong-style: false
ul-indent: false
